### ISSUE TITLE
Panel and Container Duplicate

### ISSUE THREAD

**Issue by DaveyJake** [PolymerElements/paper-header-panel#48] opened 2015-10-18 14:34 UTC
I've scoured my code, removed and replaced the affected area and I still can't figure out why this is happening.  Is anyone else experiencing this issue?

<img width="941" alt="screen shot 2015-10-18 at 8 32 14 am" src="https://cloud.githubusercontent.com/assets/826532/10564479/f664bb4c-7572-11e5-80ca-032bab8d1381.png">

I'm using `paper-header-panel v1.0.5`

**Comment by notwaldorf** [comment] 2015-10-19 02:32
Can you post a snippet of your actual code? Maybe it's something like a typo or a missing closing tag.

**Comment by blasten** [comment] 2015-10-19 05:06
@DaveyJake A jsbin will be very helpful.

**Comment by DaveyJake** [comment] 2015-10-20 15:58
I've posted my actual code on Pastebin.  Please advise.

http://pastebin.com/snss69WK

**Comment by blasten** [comment] 2015-11-25 00:28
@DaveyJake I couldn't reproduce this issue. Can you update the polymer version as well as the header-panel version to see if it's still happening?

**Comment by femiadeyemi** [comment] 2015-11-25 12:33
@DaveyJake  I think an update should fix the issue

**Comment by blasten** [comment] 2016-01-28 20:58
awesome!

**Closed as completed by blasten** 2016-01-28 20:58 UTC
Labels: pending-response
